Disable unicode in delimiter regex
This is a follow-up for cd0b916e178ee81dc45b929c27db9c285f7dc123, which
unintentionally broke Unicode-aware Perl classes such as \w and \s.

    $ tuc -e '\s+' -f 1 ...
    tuc: runtime error. The regular expression is malformed. regex parse error:
        \s+
        ^^
    error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)

When unicode is disabled for the regex, character classes such as \w
only match ASCII word characters instead of all Unicode word characters.